// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOrganizationMemberships = `-- name: CountOrganizationMemberships :one
SELECT COUNT(*) FROM organization_memberships
WHERE organization_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountOrganizationMemberships(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMemberships, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationMembershipsByStatus = `-- name: CountOrganizationMembershipsByStatus :one
SELECT COUNT(*) FROM organization_memberships
WHERE organization_id = $1
  AND status = $2
  AND deleted_at IS NULL
`

type CountOrganizationMembershipsByStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
}

func (q *Queries) CountOrganizationMembershipsByStatus(ctx context.Context, arg CountOrganizationMembershipsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMembershipsByStatus, arg.OrganizationID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMemberships = `-- name: CountUserMemberships :one
SELECT COUNT(*) FROM organization_memberships
WHERE user_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) CountUserMemberships(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMemberships, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserMembershipsByStatus = `-- name: CountUserMembershipsByStatus :one
SELECT COUNT(*) FROM organization_memberships
WHERE user_id = $1
  AND status = $2
  AND deleted_at IS NULL
`

type CountUserMembershipsByStatusParams struct {
	UserID uuid.UUID
	Status string
}

func (q *Queries) CountUserMembershipsByStatus(ctx context.Context, arg CountUserMembershipsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMembershipsByStatus, arg.UserID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizationMembership = `-- name: CreateOrganizationMembership :one
INSERT INTO organization_memberships (organization_id, user_id, role, status)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, user_id, role, status, invited_by_user_id, joined_at, created_at, updated_at
`

type CreateOrganizationMembershipParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
	Role           string
	Status         string
}

type CreateOrganizationMembershipRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) CreateOrganizationMembership(ctx context.Context, arg CreateOrganizationMembershipParams) (CreateOrganizationMembershipRow, error) {
	row := q.db.QueryRow(ctx, createOrganizationMembership,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.Status,
	)
	var i CreateOrganizationMembershipRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedByUserID,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMembershipByID = `-- name: GetOrganizationMembershipByID :one
SELECT id, organization_id, user_id, role, status, invited_by_user_id, joined_at, created_at, updated_at
FROM organization_memberships
WHERE id = $1
  AND deleted_at IS NULL
`

type GetOrganizationMembershipByIDRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetOrganizationMembershipByID(ctx context.Context, id uuid.UUID) (GetOrganizationMembershipByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembershipByID, id)
	var i GetOrganizationMembershipByIDRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedByUserID,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMembershipByOrganizationAndUser = `-- name: GetOrganizationMembershipByOrganizationAndUser :one
SELECT id, organization_id, user_id, role, status, invited_by_user_id, joined_at, created_at, updated_at
FROM organization_memberships
WHERE organization_id = $1
  AND user_id = $2
  AND deleted_at IS NULL
`

type GetOrganizationMembershipByOrganizationAndUserParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

type GetOrganizationMembershipByOrganizationAndUserRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) GetOrganizationMembershipByOrganizationAndUser(ctx context.Context, arg GetOrganizationMembershipByOrganizationAndUserParams) (GetOrganizationMembershipByOrganizationAndUserRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationMembershipByOrganizationAndUser, arg.OrganizationID, arg.UserID)
	var i GetOrganizationMembershipByOrganizationAndUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedByUserID,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizationMemberships = `-- name: ListOrganizationMemberships :many
SELECT id, organization_id, user_id, role, status, invited_by_user_id, joined_at, created_at, updated_at
FROM organization_memberships
WHERE organization_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListOrganizationMembershipsParams struct {
	OrganizationID uuid.UUID
	Limit          int32
	Offset         int32
}

type ListOrganizationMembershipsRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListOrganizationMemberships(ctx context.Context, arg ListOrganizationMembershipsParams) ([]ListOrganizationMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMemberships, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationMembershipsRow
	for rows.Next() {
		var i ListOrganizationMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.InvitedByUserID,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationMembershipsByStatus = `-- name: ListOrganizationMembershipsByStatus :many
SELECT id, organization_id, user_id, role, status, invited_by_user_id, joined_at, created_at, updated_at
FROM organization_memberships
WHERE organization_id = $1
  AND status = $2
  AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $3 OFFSET $4
`

type ListOrganizationMembershipsByStatusParams struct {
	OrganizationID uuid.UUID
	Status         string
	Limit          int32
	Offset         int32
}

type ListOrganizationMembershipsByStatusRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListOrganizationMembershipsByStatus(ctx context.Context, arg ListOrganizationMembershipsByStatusParams) ([]ListOrganizationMembershipsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembershipsByStatus,
		arg.OrganizationID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrganizationMembershipsByStatusRow
	for rows.Next() {
		var i ListOrganizationMembershipsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.InvitedByUserID,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMemberships = `-- name: ListUserMemberships :many
SELECT id, organization_id, user_id, role, status, invited_by_user_id, joined_at, created_at, updated_at
FROM organization_memberships
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type ListUserMembershipsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type ListUserMembershipsRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListUserMemberships(ctx context.Context, arg ListUserMembershipsParams) ([]ListUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listUserMemberships, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMembershipsRow
	for rows.Next() {
		var i ListUserMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.InvitedByUserID,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserMembershipsByStatus = `-- name: ListUserMembershipsByStatus :many
SELECT id, organization_id, user_id, role, status, invited_by_user_id, joined_at, created_at, updated_at
FROM organization_memberships
WHERE user_id = $1
  AND status = $2
  AND deleted_at IS NULL
ORDER BY created_at ASC
LIMIT $3 OFFSET $4
`

type ListUserMembershipsByStatusParams struct {
	UserID uuid.UUID
	Status string
	Limit  int32
	Offset int32
}

type ListUserMembershipsByStatusRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) ListUserMembershipsByStatus(ctx context.Context, arg ListUserMembershipsByStatusParams) ([]ListUserMembershipsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listUserMembershipsByStatus,
		arg.UserID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserMembershipsByStatusRow
	for rows.Next() {
		var i ListUserMembershipsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.InvitedByUserID,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrganizationMembership = `-- name: SoftDeleteOrganizationMembership :exec
UPDATE organization_memberships
SET deleted_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrganizationMembership(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteOrganizationMembership, id)
	return err
}

const updateOrganizationMembership = `-- name: UpdateOrganizationMembership :one
UPDATE organization_memberships
SET role = $2,
    status = $3,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, organization_id, user_id, role, status, invited_by_user_id, joined_at, created_at, updated_at
`

type UpdateOrganizationMembershipParams struct {
	ID     uuid.UUID
	Role   string
	Status string
}

type UpdateOrganizationMembershipRow struct {
	ID              uuid.UUID
	OrganizationID  uuid.UUID
	UserID          uuid.UUID
	Role            string
	Status          string
	InvitedByUserID pgtype.UUID
	JoinedAt        pgtype.Timestamptz
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

func (q *Queries) UpdateOrganizationMembership(ctx context.Context, arg UpdateOrganizationMembershipParams) (UpdateOrganizationMembershipRow, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMembership, arg.ID, arg.Role, arg.Status)
	var i UpdateOrganizationMembershipRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.InvitedByUserID,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
