// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountOrganizations(ctx context.Context) (int64, error)
	CountOrganizationsByStatus(ctx context.Context, status string) (int64, error)
	CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error)
	CountUsers(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountUsersByStatus(ctx context.Context, arg CountUsersByStatusParams) (int64, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByEmailForLogin(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListOrganizationsByStatus(ctx context.Context, arg ListOrganizationsByStatusParams) ([]Organization, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListUsersByStatus(ctx context.Context, arg ListUsersByStatusParams) ([]User, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
