// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*) FROM users
WHERE tenant_id = $1
  AND (name ILIKE $2 OR email ILIKE $2)
`

type CountSearchUsersParams struct {
	TenantID uuid.UUID
	Name     string
}

func (q *Queries) CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers, arg.TenantID, arg.Name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE tenant_id = $1
`

func (q *Queries) CountUsers(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByStatus = `-- name: CountUsersByStatus :one
SELECT COUNT(*) FROM users
WHERE tenant_id = $1 AND status = $2
`

type CountUsersByStatusParams struct {
	TenantID uuid.UUID
	Status   string
}

func (q *Queries) CountUsersByStatus(ctx context.Context, arg CountUsersByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByStatus, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, tenant_id, name, email, password_hash, role, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, name, email, role, status, created_at, updated_at, password_hash
`

type CreateUserParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	Role         string
	Status       string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, name, email, role, status, created_at, updated_at, password_hash FROM users
WHERE email = $1 AND tenant_id = $2
`

type GetUserByEmailParams struct {
	Email    string
	TenantID uuid.UUID
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByEmailForLogin = `-- name: GetUserByEmailForLogin :one
SELECT id, tenant_id, name, email, role, status, created_at, updated_at, password_hash FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmailForLogin(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForLogin, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, name, email, role, status, created_at, updated_at, password_hash FROM users
WHERE id = $1 AND tenant_id = $2
`

type GetUserByIDParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, tenant_id, name, email, role, status, created_at, updated_at, password_hash FROM users
WHERE tenant_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListUsersParams struct {
	TenantID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByStatus = `-- name: ListUsersByStatus :many
SELECT id, tenant_id, name, email, role, status, created_at, updated_at, password_hash FROM users
WHERE tenant_id = $1
  AND status = $2
ORDER BY name ASC
LIMIT $3 OFFSET $4
`

type ListUsersByStatusParams struct {
	TenantID uuid.UUID
	Status   string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListUsersByStatus(ctx context.Context, arg ListUsersByStatusParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByStatus,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, tenant_id, name, email, role, status, created_at, updated_at, password_hash FROM users
WHERE tenant_id = $1
  AND (name ILIKE $2 OR email ILIKE $2)
ORDER BY name ASC
LIMIT $3 OFFSET $4
`

type SearchUsersParams struct {
	TenantID uuid.UUID
	Name     string
	Limit    int32
	Offset   int32
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.TenantID,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name       = $3,
    email      = $4,
    role       = $5,
    status     = $6,
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, email, role, status, created_at, updated_at, password_hash
`

type UpdateUserParams struct {
	ID       uuid.UUID
	TenantID uuid.UUID
	Name     string
	Email    string
	Role     string
	Status   string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PasswordHash,
	)
	return i, err
}
