// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountOrganizations(ctx context.Context) (int64, error)
	CountOrganizationsByStatus(ctx context.Context, status string) (int64, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListOrganizationsByStatus(ctx context.Context, arg ListOrganizationsByStatusParams) ([]Organization, error)
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error)
}

var _ Querier = (*Queries)(nil)
